### ISSUE TITLE
error: cannot find symbol import android.provider.Telephony;

### ISSUE THREAD

**Issue by ghost** [omnirom/android_packages_apps_Dialer#3]
Okay, building for device/sony/satsuki, modded sumire tree to fit

on Dialer, this is the break

```
target Jar: wifi-service (/storage/omni/out/target/common/obj/JAVA_LIBRARIES/wifi-service_intermediates/javalib.jar)
Copying: /storage/omni/out/target/common/obj/APPS/Contacts_intermediates/emma_out/lib/classes-jarjar.jar
target Java: Dialer (/storage/omni/out/target/common/obj/APPS/Dialer_intermediates/classes)
packages/apps/Dialer/src/com/android/dialer/util/DialerUtils.java:29: error: cannot find symbol
import android.provider.Telephony;
                       ^
  symbol:   class Telephony
  location: package android.provider
packages/apps/Dialer/src/com/android/dialer/util/DialerUtils.java:104: error: package Telephony does not exist
        String smsPackage = Telephony.Sms.getDefaultSmsPackage(context);
                                     ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
build/core/java.mk:394: recipe for target '/storage/omni/out/target/common/obj/APPS/Dialer_intermediates/classes-full-debug.jar' failed
make: *** [/storage/omni/out/target/common/obj/APPS/Dialer_intermediates/classes-full-debug.jar] Error 41
make: *** Waiting for unfinished jobs....
```

Is this related to where gsm.mk comes into play, if so where/when should i be including it?
I mmm'ed Telephony , TelephonyProvider and the break is still happening

```
java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

```

This is an aarch64 build

**Comment by karthick111** [comment]
did u fix it ?

**Comment by maxwen** [comment]
No idea what you are you mixing here - but providers.Telephony is in telephony-common

**Comment by karthick111** [comment]
but still it throws errors

**Comment by ghost** [comment]
@karthick111 
I was not able to find answer equating to a "fix"
After @maxwen closed the issue, i dumped omni.

**Comment by Entropy512** [comment]
It was closed because:
1)  We don't track issues on github, we track them on Jira
2)  We only track issues on Jira for officially supported devices

None of our officially supported devices are having any problems, which indicates that this problem is in your unofficial device tree.  It's up to you, not us, to figure out what's screwed up.

**Comment by ghost** [comment]
@Entropy512 
I wasn't making a case as it being someones problem. Was just looking for a solution. No need to be testy.

**Comment by Entropy512** [comment]
I'm testy?  You're the one who is "dumping omni" because we closed an invalid issue per the criteria described above.

**Comment by ghost** [comment]
It's nothing personal or against omni. I just needed a custom build of X fast. That is all.

**Comment by name1e5s** [comment]
@ghost I'm trying to build an Omni rom for my cancro and I got the same error...did you fix it ?Thanks

**Comment by name1e5s** [comment]
@ghost After I edit Android.mk and add " telephony-common" at line57,it fixed...I don't know why but it works...
